### ISSUE TITLE
LCD support

### ISSUE THREAD

**Issue by jon-daemon** [ivomirb/Controlinator-3000#10]
I'm thinking to build one but I think this particular display you used is too expensive. Is there any other cheaper alternative that I could use? I have found the ST7567S which is also I2C. Would that work with some modifications?

I have built something similar [here](https://github.com/jon-daemon/cncjs-pendant) but it's for CNCjs. I'd like to try yours to have the WCS position on the display. Also I don't use the joystick and I might eliminate that. The encoder works fine for me.

**Comment by ivomirb** [comment]
A smaller screen will definitely work, as long as it has the necessary resolution. I wanted the largest screen I could find so it is easier on the eyes and so that the buttons will roughly match the text location. If reading the small text is not an issue for you, go for it.

The joystick is certainly optional. You should remove the code that reads the X and Y positions, or it will think that the joystick is pushed to the corner. Just remove the body of the function UpdateJoystick in input.h.

**Comment by jon-daemon** [comment]
Thank you, I will try to build it with some modifications in the next month and report back.
